### ISSUE TITLE
Faced some error while using train.py in accelerate. Do you have some suggestions?

### ISSUE THREAD

**Issue by LT1st** [CXH-Research/IRFormer#4]
Faced some error while using train.py in accelerate. Do you have some suggestions?
```
ry Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-04-22 08:21:02,748] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 170874) of binary: /home/spai/anaconda3/envs/irfomer_t/bin/python
Traceback (most recent call last):
  File "/home/spai/anaconda3/envs/irfomer_t/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/spai/anaconda3/envs/irfomer_t/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/spai/anaconda3/envs/irfomer_t/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1048, in launch_command
    multi_gpu_launcher(args)
  File "/home/spai/anaconda3/envs/irfomer_t/lib/python3.8/site-packages/accelerate/commands/launch.py", line 702, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/spai/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/spai/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/spai/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-22_08:21:02
  host      : spai-WS-E900-G4-WS980T
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 170875)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-22_08:21:02
  host      : spai-WS-E900-G4-WS980T
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 170874)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by xuhangc** [comment]
can you provide a full error log?

**Comment by xuhangc** [comment]
You can add my WeChat lkljty
